Add: upload files
wecode-bootcamp-korea/10-React-Westagram-3 pull request #2
Opened 2020-07-09 01:54 UTC by limo-sum

3팀 이지윤 파일 업로드합니다.

2020-07-09 05:46 UTC, joonsikyang reviewed
리뷰 내용 반영해서 수정 부탁드립니다!

---

✔️ 현재 컴포넌트 이름이 동일해서 css 깨지는 문제가 발생하고 있습니다. 
최상위 요소의 className은 세션때 이야기했듯이 보통 컴포넌트 이름과 같게 해주지만 이번 프로젝트의 경우에는 `컴포넌트_이름` 이런식으로 작성해주셔야 될 것 같습니다. 전부 수정 부탁드릴게요 👐

ex. `.Login` >> `.Login_JS` /  `.Main` >> `.Main_JS`

2020-07-09 05:46 UTC, joonsikyang commented on src/Pages/JIYUNLEE/Login/Login.js
> +  }
가독성 위해서 함수 위아래로 한 줄 씩 띄워주세요!

2020-07-09 05:46 UTC, joonsikyang commented on src/Pages/JIYUNLEE/Login/Login.js
> +      <div class="Login">
className

2020-07-09 05:46 UTC, joonsikyang commented on src/Pages/JIYUNLEE/Main/MainRight/MainRight.js
> +export default MainRight;
export 구문도 한 줄 띄워주세요

2020-07-09 05:46 UTC, joonsikyang commented on src/Pages/JIYUNLEE/Main/MainRight/MainRight.scss
> +}
위와 같은 속성은 reset.scss로 이동시켜주시고 팀원들과도 상의해주세요 :)
(reset.scss는 index.js에서 import 해주세요)

2020-07-09 05:46 UTC, joonsikyang commented on src/Pages/JIYUNLEE/Main/MainRight/MainRight.js
> +      <div>
이미 mainRight 요소로 감싸져 있어서 불필요한 div 태그 같네요! 지워주세요

2020-07-09 05:46 UTC, joonsikyang commented on src/Pages/JIYUNLEE/Main/MainRight/MainRight.js
> +        <div className="mainRight">
최상위 요소라는 것을 표시하기 위해서 컴포넌트 이름처럼 대문자로 시작해주세요!

2020-07-09 05:46 UTC, joonsikyang commented on src/Pages/JIYUNLEE/Main/MainRight/MainRight.scss
> +}
이 부분도 nesting 되어 있지 않으면 다른 파일에도 영향을 줄 수 있습니다. 팀원들과 상의해서 reset.scss로 옮겨주시거나 최상위 요소 안 쪽으로 nesting 시켜주세요!

2020-07-09 05:46 UTC, joonsikyang commented on src/Pages/JIYUNLEE/Main/Nav/Nav.js
> +      <nav>
이 부분도 className이 없으면 다른 파일과 css가 꼬일 수 있어요! className 부여해주시고 nesting 잘 될 수 있도록 해주세요.

2020-07-09 05:46 UTC, joonsikyang commented on src/Pages/JIYUNLEE/Main/Nav/Nav.scss
> +}
reset.scss

2020-07-09 05:46 UTC, joonsikyang commented on src/Pages/JIYUNLEE/Main/Nav/Nav.scss
> +    }
wildcard tag(`*`) 에 이런 속성을 부여하는 것은 위험합니다! 그리고 22번째 줄에 이미 `. navContent` 에 배경 색상을 부여해주셔서 필요 없어 보이네요!

2020-07-09 05:46 UTC, joonsikyang commented on src/Route.js
> +import jiyunLogin from "./Pages/JIYUNLEE/Login/Login";
지윤로그인도 경로 설정해주세요 :)

2020-07-09 07:07 UTC, limo-sum commented on src/Pages/JIYUNLEE/Main/Nav/Nav.scss
> +}
reset.scss 사용하지 않고 일부 필요한 부분에만 적용했습니다!

2020-07-09 07:38 UTC, rudqo14 commented on src/Pages/JIYUNLEE/Main/Feeds/Feeds.scss
> +          }
카멜 표기법이 아닌 이유가 있나요?

2020-07-09 12:45 UTC, ghost commented on src/Pages/JIYUNLEE/Main/Feeds/Feeds.scss
> +        .idmore {
카멜 표기법이 아닌 이유가 있나요?

2020-07-09 12:47 UTC, limo-sum commented on src/Pages/JIYUNLEE/Main/Feeds/Feeds.scss
> +        .idmore {
변경하겠습니다 😅

2020-07-09 16:11 UTC, jamessoun93 commented on src/Pages/JIYUNLEE/Main/Feeds/Feeds.scss
> +        .idmore {
👍👍👍👍

2020-07-09 16:14 UTC, jamessoun93 commented on src/Pages/JIYUNLEE/Main/Feeds/Feeds.scss
> +        .idmore {
경배님 리뷰 반영해서 push 해주세요!

2020-07-09 16:14 UTC, jamessoun93 approved these changes

2020-07-09 16:23 UTC, jamessoun93 requested changes

2020-07-09 16:23 UTC, jamessoun93 commented on src/Pages/JIYUNLEE/Login/Login.js
> +  }
박수 👏👏👏

각 메서드들 사이에 공백만 추가해주시면 더 좋을 것 같네요!

2020-07-09 16:23 UTC, jamessoun93 commented on src/Pages/JIYUNLEE/Login/Login.js
> +    }
두 console.log 문이 둘다 중괄호에 감싸져 있는 이유가 있나요?

2020-07-09 16:23 UTC, jamessoun93 commented on src/Pages/JIYUNLEE/Login/Login.js
> +    const isEnabled = this.canBeSubmitted();
아래 한칸 띄워주세요!

2020-07-09 16:23 UTC, jamessoun93 commented on src/Pages/JIYUNLEE/Main/Feeds/Feeds.scss
> +        div img {
구분을 위해 한줄씩 띄워주세요!

2020-07-10 01:20 UTC, limo-sum commented on src/Pages/JIYUNLEE/Login/Login.js
> +    }
중괄호 삭제했습니다!

2020-07-10 02:54 UTC, jamessoun93 commented
LGTM 🎉🎉🎉

2020-07-10 02:54 UTC, merged